import turtle
turtle.setup(900,600,200,200)
turtle.bgcolor("red")
turtle.fillcolor("yellow")
turtle.color("yellow")
turtle.begin_fill()
turtle.up()
turtle.goto(-390,180)
turtle.down()
for i in range(5):
    turtle.fd(150)
    turtle.right(144)
turtle.end_fill()
turtle.begin_fill()
turtle.up()
turtle.goto(-174,48)
turtle.seth(330)
turtle.down()
for i in range(5):
    turtle.fd(50)
    turtle.right(144)
turtle.end_fill()
turtle.begin_fill()
turtle.up()
turtle.goto(-117,96)
turtle.seth(0)
turtle.down()
for i in range(5):
    turtle.fd(50)
    turtle.right(144)
turtle.end_fill()
turtle.begin_fill()
turtle.up()
turtle.goto(-117,174)
turtle.seth(25)
turtle.down()
for i in range(5):
    turtle.fd(50)
    turtle.right(144)
turtle.end_fill()
turtle.begin_fill()
turtle.up()
turtle.goto(-174,258)
turtle.seth(330)
turtle.down()
for i in range(5):
    turtle.fd(50)
    turtle.right(144)
turtle.end_fill()
